### ISSUE TITLE
surface of revolution

### ISSUE THREAD

**Issue by GeneKao** [compas-dev/compas_occ#17]
# Feature Request

@brgcode @Licini Is it possible to wrap revolve function? So we have more ways to create surfaces.
Something like this one: 
https://dev.opencascade.org/doc/refman/html/class_geom___surface_of_revolution.html

Thanks!

**Comment by tomvanmele** [comment]
yes, no problem

**Comment by tomvanmele** [comment]
not the most exciting surface ever :)

<img width="912" alt="Screenshot 2022-04-27 at 17 28 56" src="https://user-images.githubusercontent.com/29653489/165554984-9348217e-e24b-41df-a227-9cefad28bc16.png">

**Comment by GeneKao** [comment]
nice! very cool! 🥳

**Comment by tomvanmele** [comment]
available since 2eed691fcddeeaacc1698418b5439c87407670fb
